### ISSUE TITLE
Using --watch-stdin causes an error on exit

### ISSUE THREAD

**Issue by moubi** [moubi/es6-project-template#2]
When running webpack server in watch mode with `--watch-stdin` (see https://github.com/webpack/webpack/pull/1311 for a ref) and exit it after, it throws an error:

```
throw er; // Unhandled 'error' event
      ^

Error: read EIO
    at exports._errnoException (util.js:1007:11)
    at TTY.onread (net.js:563:26)
```

Running without `--watch-stdin` solves the problem, but then it doesn't kill the webpack server process. With that said I think the problem is related to `--watch-stdin`.

Needs confirmation.

**Comment by moubi** [comment]
Starting `webpack-dev-server` with `--watch` instead of `--watch-stdin` seems to work. 
Anyway the second problem described above appears: after exit of webpack it does not kill the process, so the server can not be started again on the same port.

@moonflare @Volzy @nprasmussen if some of you have experienced the issue outlined, please share thoughts.
